version: "3"
services:
  broker:
    image: eclipse-mosquitto
    volumes:
      - "./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
    networks:
      - localnet
    ports:
      - "1883:1883"
      - "9001:9001"
  node-red:
    depends_on:
      - broker
    image: nodered/node-red
    volumes:
      - "./node-red:/data"
    user: "0"
    networks:
      - localnet
    ports:
      - "1880:1880"
networks:
  localnet: