#include "Arduino.h"

#define SECRET_NET_SSID ""
#define SECRET_NET_PASSWORD ""
#define SECRET_MQTT_SERVER ""
#define SECRET_MQTT_PORT 1883
#define SECRET_OPTIONAL_MQTT_USERNAME NULL
#define SECRET_OPTIONAL_MQTT_PASSWORD NULL
